# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.primme_initialize <- function() {
    .Call('Primme_primme_initialize_rcpp', PACKAGE = 'Primme')
}

.primme_free <- function(primme) {
    invisible(.Call('Primme_primme_free_rcpp', PACKAGE = 'Primme', primme))
}

.primme_set_method <- function(methodstr, primme) {
    invisible(.Call('Primme_primme_set_method_rcpp', PACKAGE = 'Primme', methodstr, primme))
}

.primme_get_member <- function(labelstr, primme) {
    .Call('Primme_primme_get_member_rcpp', PACKAGE = 'Primme', labelstr, primme)
}

.primme_set_member <- function(labelstr, value, primme) {
    invisible(.Call('Primme_primme_set_member_rcpp', PACKAGE = 'Primme', labelstr, value, primme))
}

.dprimme <- function(ortho, init, A, B, prec, convTest, primme) {
    .Call('Primme_dprimme_rcpp', PACKAGE = 'Primme', ortho, init, A, B, prec, convTest, primme)
}

.zprimme <- function(ortho, init, A, B, prec, convTest, primme) {
    .Call('Primme_zprimme_rcpp', PACKAGE = 'Primme', ortho, init, A, B, prec, convTest, primme)
}

.primme_svds_initialize <- function() {
    .Call('Primme_primme_svds_initialize_rcpp', PACKAGE = 'Primme')
}

.primme_svds_free <- function(primme_svds) {
    invisible(.Call('Primme_primme_svds_free_rcpp', PACKAGE = 'Primme', primme_svds))
}

.primme_svds_set_method <- function(methodstr, methodStage1str, methodStage2str, primme_svds) {
    invisible(.Call('Primme_primme_svds_set_method_rcpp', PACKAGE = 'Primme', methodstr, methodStage1str, methodStage2str, primme_svds))
}

.primme_svds_get_member <- function(labelstr, primme_svds) {
    .Call('Primme_primme_svds_get_member_rcpp', PACKAGE = 'Primme', labelstr, primme_svds)
}

.primme_svds_set_member <- function(labelstr, value, primme_svds) {
    invisible(.Call('Primme_primme_svds_set_member_rcpp', PACKAGE = 'Primme', labelstr, value, primme_svds))
}

.dprimme_svds <- function(orthol, orthor, initl, initr, A, prec, primme_svds) {
    .Call('Primme_dprimme_svds_rcpp', PACKAGE = 'Primme', orthol, orthor, initl, initr, A, prec, primme_svds)
}

.zprimme_svds <- function(orthol, orthor, initl, initr, A, prec, primme_svds) {
    .Call('Primme_zprimme_svds_rcpp', PACKAGE = 'Primme', orthol, orthor, initl, initr, A, prec, primme_svds)
}

