/*******************************************************************************
 *   PRIMME PReconditioned Iterative MultiMethod Eigensolver
 *   Copyright (C) 2015 College of William & Mary,
 *   James R. McCombs, Eloy Romero Alcalde, Andreas Stathopoulos, Lingfei Wu
 *
 *   This file is part of PRIMME.
 *
 *   PRIMME is free software; you can redistribute it and/or
 *   modify it under the terms of the GNU Lesser General Public
 *   License as published by the Free Software Foundation; either
 *   version 2.1 of the License, or (at your option) any later version.
 *
 *   PRIMME is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *   Lesser General Public License for more details.
 *
 *   You should have received a copy of the GNU Lesser General Public
 *   License along with this library; if not, write to the Free Software
 *   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 *******************************************************************************
 *   NOTE: THIS FILE IS AUTOMATICALLY GENERATED. PLEASE DON'T MODIFY
 ******************************************************************************/


#ifndef inner_solve_H
#define inner_solve_H
#if !defined(CHECK_TEMPLATE) && !defined(inner_solve_Sprimme)
#  define inner_solve_Sprimme CONCAT(inner_solve_,SCALAR_SUF)
#endif
#if !defined(CHECK_TEMPLATE) && !defined(inner_solve_Rprimme)
#  define inner_solve_Rprimme CONCAT(inner_solve_,REAL_SUF)
#endif
int inner_solve_dprimme(double *x, double *r, double *rnorm,
   double *evecs, double *evecsHat, double *UDU, int *ipivot,
   double *xKinvx, double *Lprojector, double *RprojectorQ,
   double *RprojectorX, int sizeLprojector, int sizeRprojectorQ,
   int sizeRprojectorX, double *sol, double eval, double shift,
   double eresTol, double aNormEstimate, double machEps, double *rwork,
   size_t rworkSize, primme_params *primme);
int inner_solve_zprimme(_Complex double *x, _Complex double *r, double *rnorm,
   _Complex double *evecs, _Complex double *evecsHat, _Complex double *UDU, int *ipivot,
   _Complex double *xKinvx, _Complex double *Lprojector, _Complex double *RprojectorQ,
   _Complex double *RprojectorX, int sizeLprojector, int sizeRprojectorQ,
   int sizeRprojectorX, _Complex double *sol, double eval, double shift,
   double eresTol, double aNormEstimate, double machEps, _Complex double *rwork,
   size_t rworkSize, primme_params *primme);
int inner_solve_sprimme(float *x, float *r, float *rnorm,
   float *evecs, float *evecsHat, float *UDU, int *ipivot,
   float *xKinvx, float *Lprojector, float *RprojectorQ,
   float *RprojectorX, int sizeLprojector, int sizeRprojectorQ,
   int sizeRprojectorX, float *sol, float eval, float shift,
   double eresTol, double aNormEstimate, double machEps, float *rwork,
   size_t rworkSize, primme_params *primme);
int inner_solve_cprimme(_Complex float *x, _Complex float *r, float *rnorm,
   _Complex float *evecs, _Complex float *evecsHat, _Complex float *UDU, int *ipivot,
   _Complex float *xKinvx, _Complex float *Lprojector, _Complex float *RprojectorQ,
   _Complex float *RprojectorX, int sizeLprojector, int sizeRprojectorQ,
   int sizeRprojectorX, _Complex float *sol, float eval, float shift,
   double eresTol, double aNormEstimate, double machEps, _Complex float *rwork,
   size_t rworkSize, primme_params *primme);
#endif
