/*******************************************************************************
 * Copyright (c) 2018, College of William & Mary
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the College of William & Mary nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COLLEGE OF WILLIAM & MARY BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 * PRIMME: https://github.com/primme/primme
 * Contact: Andreas Stathopoulos, a n d r e a s _at_ c s . w m . e d u
 *******************************************************************************
 *   NOTE: THIS FILE IS AUTOMATICALLY GENERATED. PLEASE DON'T MODIFY
 ******************************************************************************/


#ifndef magma_wrapper_H
#define magma_wrapper_H
int Num_malloc_magma_sprimme(PRIMME_INT n, dummy_type_magma_sprimme **x, primme_context ctx);
int Num_free_magma_sprimme(dummy_type_magma_sprimme *x, primme_context ctx);
int Num_copy_Tmatrix_magma_sprimme(void *x, primme_op_datatype xt, PRIMME_INT m,
      PRIMME_INT n, PRIMME_INT ldx, dummy_type_magma_sprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_copy_magma_sprimme(PRIMME_INT n, dummy_type_magma_sprimme *x, int incx, dummy_type_magma_sprimme *y, int incy,
      primme_context ctx);
int Num_gemm_magma_sprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_sprimme alpha, dummy_type_magma_sprimme *a, int lda, dummy_type_magma_sprimme *b, int ldb,
      dummy_type_sprimme beta, dummy_type_magma_sprimme *c, int ldc, primme_context ctx);
int Num_gemm_dhd_magma_sprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_sprimme alpha, dummy_type_magma_sprimme *a, int lda, dummy_type_sprimme *b, int ldb,
      dummy_type_sprimme beta, dummy_type_magma_sprimme *c, int ldc, primme_context ctx);
int Num_gemm_ddh_magma_sprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_sprimme alpha, dummy_type_magma_sprimme *a, int lda, dummy_type_magma_sprimme *b, int ldb,
      dummy_type_sprimme beta, dummy_type_sprimme *c, int ldc, primme_context ctx);
int Num_gemv_magma_sprimme(const char *transa, PRIMME_INT m, int n, dummy_type_sprimme alpha,
      dummy_type_magma_sprimme *a, int lda, dummy_type_magma_sprimme *x, int incx, dummy_type_sprimme beta, dummy_type_magma_sprimme *y,
      int incy, primme_context ctx);
int Num_gemv_ddh_magma_sprimme(const char *transa, PRIMME_INT m, int n, dummy_type_sprimme alpha,
      dummy_type_magma_sprimme *a, int lda, dummy_type_magma_sprimme *x, int incx, dummy_type_sprimme beta, dummy_type_sprimme *y,
      int incy, primme_context ctx);
int Num_gemv_dhd_magma_sprimme(const char *transa, PRIMME_INT m, int n, dummy_type_sprimme alpha,
      dummy_type_magma_sprimme *a, int lda, dummy_type_sprimme *x, int incx, dummy_type_sprimme beta, dummy_type_magma_sprimme *y,
      int incy, primme_context ctx);
int Num_axpy_magma_sprimme(PRIMME_INT n, dummy_type_sprimme alpha, dummy_type_magma_sprimme *x, int incx,
   dummy_type_magma_sprimme *y, int incy, primme_context ctx);
dummy_type_sprimme Num_dot_magma_sprimme(PRIMME_INT n, dummy_type_magma_sprimme *x, int incx, dummy_type_magma_sprimme *y, int incy,
      primme_context ctx);
int Num_scal_magma_sprimme(PRIMME_INT n, dummy_type_sprimme alpha, dummy_type_magma_sprimme *x, int incx,
      primme_context ctx);
int Num_larnv_magma_sprimme(int idist, PRIMME_INT *iseed, PRIMME_INT length,
      dummy_type_magma_sprimme *x, primme_context ctx);
int Num_copy_matrix_magma_sprimme(dummy_type_magma_sprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, dummy_type_magma_sprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_zero_matrix_magma_sprimme(dummy_type_magma_sprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, primme_context ctx);
int Num_trsm_hd_magma_sprimme(const char *side, const char *uplo, const char *transa,
      const char *diag, int m, int n, dummy_type_sprimme alpha, dummy_type_sprimme *a, int lda,
      dummy_type_magma_sprimme *b, int ldb, primme_context ctx);
int Num_malloc_magma_cprimme(PRIMME_INT n, dummy_type_magma_cprimme **x, primme_context ctx);
int Num_free_magma_cprimme(dummy_type_magma_cprimme *x, primme_context ctx);
int Num_copy_Tmatrix_magma_cprimme(void *x, primme_op_datatype xt, PRIMME_INT m,
      PRIMME_INT n, PRIMME_INT ldx, dummy_type_magma_cprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_copy_magma_cprimme(PRIMME_INT n, dummy_type_magma_cprimme *x, int incx, dummy_type_magma_cprimme *y, int incy,
      primme_context ctx);
int Num_gemm_magma_cprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_cprimme alpha, dummy_type_magma_cprimme *a, int lda, dummy_type_magma_cprimme *b, int ldb,
      dummy_type_cprimme beta, dummy_type_magma_cprimme *c, int ldc, primme_context ctx);
int Num_gemm_dhd_magma_cprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_cprimme alpha, dummy_type_magma_cprimme *a, int lda, dummy_type_cprimme *b, int ldb,
      dummy_type_cprimme beta, dummy_type_magma_cprimme *c, int ldc, primme_context ctx);
int Num_gemm_ddh_magma_cprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_cprimme alpha, dummy_type_magma_cprimme *a, int lda, dummy_type_magma_cprimme *b, int ldb,
      dummy_type_cprimme beta, dummy_type_cprimme *c, int ldc, primme_context ctx);
int Num_gemv_magma_cprimme(const char *transa, PRIMME_INT m, int n, dummy_type_cprimme alpha,
      dummy_type_magma_cprimme *a, int lda, dummy_type_magma_cprimme *x, int incx, dummy_type_cprimme beta, dummy_type_magma_cprimme *y,
      int incy, primme_context ctx);
int Num_gemv_ddh_magma_cprimme(const char *transa, PRIMME_INT m, int n, dummy_type_cprimme alpha,
      dummy_type_magma_cprimme *a, int lda, dummy_type_magma_cprimme *x, int incx, dummy_type_cprimme beta, dummy_type_cprimme *y,
      int incy, primme_context ctx);
int Num_gemv_dhd_magma_cprimme(const char *transa, PRIMME_INT m, int n, dummy_type_cprimme alpha,
      dummy_type_magma_cprimme *a, int lda, dummy_type_cprimme *x, int incx, dummy_type_cprimme beta, dummy_type_magma_cprimme *y,
      int incy, primme_context ctx);
int Num_axpy_magma_cprimme(PRIMME_INT n, dummy_type_cprimme alpha, dummy_type_magma_cprimme *x, int incx,
   dummy_type_magma_cprimme *y, int incy, primme_context ctx);
dummy_type_cprimme Num_dot_magma_cprimme(PRIMME_INT n, dummy_type_magma_cprimme *x, int incx, dummy_type_magma_cprimme *y, int incy,
      primme_context ctx);
int Num_scal_magma_cprimme(PRIMME_INT n, dummy_type_cprimme alpha, dummy_type_magma_cprimme *x, int incx,
      primme_context ctx);
int Num_larnv_magma_cprimme(int idist, PRIMME_INT *iseed, PRIMME_INT length,
      dummy_type_magma_cprimme *x, primme_context ctx);
int Num_copy_matrix_magma_cprimme(dummy_type_magma_cprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, dummy_type_magma_cprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_zero_matrix_magma_cprimme(dummy_type_magma_cprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, primme_context ctx);
int Num_trsm_hd_magma_cprimme(const char *side, const char *uplo, const char *transa,
      const char *diag, int m, int n, dummy_type_cprimme alpha, dummy_type_cprimme *a, int lda,
      dummy_type_magma_cprimme *b, int ldb, primme_context ctx);
int Num_malloc_magma_dprimme(PRIMME_INT n, dummy_type_magma_dprimme **x, primme_context ctx);
int Num_free_magma_dprimme(dummy_type_magma_dprimme *x, primme_context ctx);
int Num_copy_Tmatrix_magma_dprimme(void *x, primme_op_datatype xt, PRIMME_INT m,
      PRIMME_INT n, PRIMME_INT ldx, dummy_type_magma_dprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_copy_magma_dprimme(PRIMME_INT n, dummy_type_magma_dprimme *x, int incx, dummy_type_magma_dprimme *y, int incy,
      primme_context ctx);
int Num_gemm_magma_dprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_dprimme alpha, dummy_type_magma_dprimme *a, int lda, dummy_type_magma_dprimme *b, int ldb,
      dummy_type_dprimme beta, dummy_type_magma_dprimme *c, int ldc, primme_context ctx);
int Num_gemm_dhd_magma_dprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_dprimme alpha, dummy_type_magma_dprimme *a, int lda, dummy_type_dprimme *b, int ldb,
      dummy_type_dprimme beta, dummy_type_magma_dprimme *c, int ldc, primme_context ctx);
int Num_gemm_ddh_magma_dprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_dprimme alpha, dummy_type_magma_dprimme *a, int lda, dummy_type_magma_dprimme *b, int ldb,
      dummy_type_dprimme beta, dummy_type_dprimme *c, int ldc, primme_context ctx);
int Num_gemv_magma_dprimme(const char *transa, PRIMME_INT m, int n, dummy_type_dprimme alpha,
      dummy_type_magma_dprimme *a, int lda, dummy_type_magma_dprimme *x, int incx, dummy_type_dprimme beta, dummy_type_magma_dprimme *y,
      int incy, primme_context ctx);
int Num_gemv_ddh_magma_dprimme(const char *transa, PRIMME_INT m, int n, dummy_type_dprimme alpha,
      dummy_type_magma_dprimme *a, int lda, dummy_type_magma_dprimme *x, int incx, dummy_type_dprimme beta, dummy_type_dprimme *y,
      int incy, primme_context ctx);
int Num_gemv_dhd_magma_dprimme(const char *transa, PRIMME_INT m, int n, dummy_type_dprimme alpha,
      dummy_type_magma_dprimme *a, int lda, dummy_type_dprimme *x, int incx, dummy_type_dprimme beta, dummy_type_magma_dprimme *y,
      int incy, primme_context ctx);
int Num_axpy_magma_dprimme(PRIMME_INT n, dummy_type_dprimme alpha, dummy_type_magma_dprimme *x, int incx,
   dummy_type_magma_dprimme *y, int incy, primme_context ctx);
dummy_type_dprimme Num_dot_magma_dprimme(PRIMME_INT n, dummy_type_magma_dprimme *x, int incx, dummy_type_magma_dprimme *y, int incy,
      primme_context ctx);
int Num_scal_magma_dprimme(PRIMME_INT n, dummy_type_dprimme alpha, dummy_type_magma_dprimme *x, int incx,
      primme_context ctx);
int Num_larnv_magma_dprimme(int idist, PRIMME_INT *iseed, PRIMME_INT length,
      dummy_type_magma_dprimme *x, primme_context ctx);
int Num_copy_matrix_magma_dprimme(dummy_type_magma_dprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, dummy_type_magma_dprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_zero_matrix_magma_dprimme(dummy_type_magma_dprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, primme_context ctx);
int Num_trsm_hd_magma_dprimme(const char *side, const char *uplo, const char *transa,
      const char *diag, int m, int n, dummy_type_dprimme alpha, dummy_type_dprimme *a, int lda,
      dummy_type_magma_dprimme *b, int ldb, primme_context ctx);
int Num_malloc_magma_zprimme(PRIMME_INT n, dummy_type_magma_zprimme **x, primme_context ctx);
int Num_free_magma_zprimme(dummy_type_magma_zprimme *x, primme_context ctx);
int Num_copy_Tmatrix_magma_zprimme(void *x, primme_op_datatype xt, PRIMME_INT m,
      PRIMME_INT n, PRIMME_INT ldx, dummy_type_magma_zprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_copy_magma_zprimme(PRIMME_INT n, dummy_type_magma_zprimme *x, int incx, dummy_type_magma_zprimme *y, int incy,
      primme_context ctx);
int Num_gemm_magma_zprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_zprimme alpha, dummy_type_magma_zprimme *a, int lda, dummy_type_magma_zprimme *b, int ldb,
      dummy_type_zprimme beta, dummy_type_magma_zprimme *c, int ldc, primme_context ctx);
int Num_gemm_dhd_magma_zprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_zprimme alpha, dummy_type_magma_zprimme *a, int lda, dummy_type_zprimme *b, int ldb,
      dummy_type_zprimme beta, dummy_type_magma_zprimme *c, int ldc, primme_context ctx);
int Num_gemm_ddh_magma_zprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_zprimme alpha, dummy_type_magma_zprimme *a, int lda, dummy_type_magma_zprimme *b, int ldb,
      dummy_type_zprimme beta, dummy_type_zprimme *c, int ldc, primme_context ctx);
int Num_gemv_magma_zprimme(const char *transa, PRIMME_INT m, int n, dummy_type_zprimme alpha,
      dummy_type_magma_zprimme *a, int lda, dummy_type_magma_zprimme *x, int incx, dummy_type_zprimme beta, dummy_type_magma_zprimme *y,
      int incy, primme_context ctx);
int Num_gemv_ddh_magma_zprimme(const char *transa, PRIMME_INT m, int n, dummy_type_zprimme alpha,
      dummy_type_magma_zprimme *a, int lda, dummy_type_magma_zprimme *x, int incx, dummy_type_zprimme beta, dummy_type_zprimme *y,
      int incy, primme_context ctx);
int Num_gemv_dhd_magma_zprimme(const char *transa, PRIMME_INT m, int n, dummy_type_zprimme alpha,
      dummy_type_magma_zprimme *a, int lda, dummy_type_zprimme *x, int incx, dummy_type_zprimme beta, dummy_type_magma_zprimme *y,
      int incy, primme_context ctx);
int Num_axpy_magma_zprimme(PRIMME_INT n, dummy_type_zprimme alpha, dummy_type_magma_zprimme *x, int incx,
   dummy_type_magma_zprimme *y, int incy, primme_context ctx);
dummy_type_zprimme Num_dot_magma_zprimme(PRIMME_INT n, dummy_type_magma_zprimme *x, int incx, dummy_type_magma_zprimme *y, int incy,
      primme_context ctx);
int Num_scal_magma_zprimme(PRIMME_INT n, dummy_type_zprimme alpha, dummy_type_magma_zprimme *x, int incx,
      primme_context ctx);
int Num_larnv_magma_zprimme(int idist, PRIMME_INT *iseed, PRIMME_INT length,
      dummy_type_magma_zprimme *x, primme_context ctx);
int Num_copy_matrix_magma_zprimme(dummy_type_magma_zprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, dummy_type_magma_zprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_zero_matrix_magma_zprimme(dummy_type_magma_zprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, primme_context ctx);
int Num_trsm_hd_magma_zprimme(const char *side, const char *uplo, const char *transa,
      const char *diag, int m, int n, dummy_type_zprimme alpha, dummy_type_zprimme *a, int lda,
      dummy_type_magma_zprimme *b, int ldb, primme_context ctx);
int Num_malloc_magma_hprimme(PRIMME_INT n, dummy_type_magma_hprimme **x, primme_context ctx);
int Num_free_magma_hprimme(dummy_type_magma_hprimme *x, primme_context ctx);
int Num_copy_Tmatrix_magma_hprimme(void *x, primme_op_datatype xt, PRIMME_INT m,
      PRIMME_INT n, PRIMME_INT ldx, dummy_type_magma_hprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_copy_magma_hprimme(PRIMME_INT n, dummy_type_magma_hprimme *x, int incx, dummy_type_magma_hprimme *y, int incy,
      primme_context ctx);
int Num_gemm_magma_hprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_sprimme alpha, dummy_type_magma_hprimme *a, int lda, dummy_type_magma_hprimme *b, int ldb,
      dummy_type_sprimme beta, dummy_type_magma_hprimme *c, int ldc, primme_context ctx);
int Num_gemm_dhd_magma_hprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_sprimme alpha, dummy_type_magma_hprimme *a, int lda, dummy_type_sprimme *b, int ldb,
      dummy_type_sprimme beta, dummy_type_magma_hprimme *c, int ldc, primme_context ctx);
int Num_gemm_ddh_magma_hprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_sprimme alpha, dummy_type_magma_hprimme *a, int lda, dummy_type_magma_hprimme *b, int ldb,
      dummy_type_sprimme beta, dummy_type_sprimme *c, int ldc, primme_context ctx);
int Num_gemv_magma_hprimme(const char *transa, PRIMME_INT m, int n, dummy_type_sprimme alpha,
      dummy_type_magma_hprimme *a, int lda, dummy_type_magma_hprimme *x, int incx, dummy_type_sprimme beta, dummy_type_magma_hprimme *y,
      int incy, primme_context ctx);
int Num_gemv_ddh_magma_hprimme(const char *transa, PRIMME_INT m, int n, dummy_type_sprimme alpha,
      dummy_type_magma_hprimme *a, int lda, dummy_type_magma_hprimme *x, int incx, dummy_type_sprimme beta, dummy_type_sprimme *y,
      int incy, primme_context ctx);
int Num_gemv_dhd_magma_hprimme(const char *transa, PRIMME_INT m, int n, dummy_type_sprimme alpha,
      dummy_type_magma_hprimme *a, int lda, dummy_type_sprimme *x, int incx, dummy_type_sprimme beta, dummy_type_magma_hprimme *y,
      int incy, primme_context ctx);
int Num_axpy_magma_hprimme(PRIMME_INT n, dummy_type_sprimme alpha, dummy_type_magma_hprimme *x, int incx,
   dummy_type_magma_hprimme *y, int incy, primme_context ctx);
dummy_type_sprimme Num_dot_magma_hprimme(PRIMME_INT n, dummy_type_magma_hprimme *x, int incx, dummy_type_magma_hprimme *y, int incy,
      primme_context ctx);
int Num_scal_magma_hprimme(PRIMME_INT n, dummy_type_sprimme alpha, dummy_type_magma_hprimme *x, int incx,
      primme_context ctx);
int Num_larnv_magma_hprimme(int idist, PRIMME_INT *iseed, PRIMME_INT length,
      dummy_type_magma_hprimme *x, primme_context ctx);
int Num_copy_matrix_magma_hprimme(dummy_type_magma_hprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, dummy_type_magma_hprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_zero_matrix_magma_hprimme(dummy_type_magma_hprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, primme_context ctx);
int Num_trsm_hd_magma_hprimme(const char *side, const char *uplo, const char *transa,
      const char *diag, int m, int n, dummy_type_sprimme alpha, dummy_type_sprimme *a, int lda,
      dummy_type_magma_hprimme *b, int ldb, primme_context ctx);
int Num_malloc_magma_kprimme(PRIMME_INT n, dummy_type_magma_kprimme **x, primme_context ctx);
int Num_free_magma_kprimme(dummy_type_magma_kprimme *x, primme_context ctx);
int Num_copy_Tmatrix_magma_kprimme(void *x, primme_op_datatype xt, PRIMME_INT m,
      PRIMME_INT n, PRIMME_INT ldx, dummy_type_magma_kprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_copy_magma_kprimme(PRIMME_INT n, dummy_type_magma_kprimme *x, int incx, dummy_type_magma_kprimme *y, int incy,
      primme_context ctx);
int Num_gemm_magma_kprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_cprimme alpha, dummy_type_magma_kprimme *a, int lda, dummy_type_magma_kprimme *b, int ldb,
      dummy_type_cprimme beta, dummy_type_magma_kprimme *c, int ldc, primme_context ctx);
int Num_gemm_dhd_magma_kprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_cprimme alpha, dummy_type_magma_kprimme *a, int lda, dummy_type_cprimme *b, int ldb,
      dummy_type_cprimme beta, dummy_type_magma_kprimme *c, int ldc, primme_context ctx);
int Num_gemm_ddh_magma_kprimme(const char *transa, const char *transb, int m, int n,
      int k, dummy_type_cprimme alpha, dummy_type_magma_kprimme *a, int lda, dummy_type_magma_kprimme *b, int ldb,
      dummy_type_cprimme beta, dummy_type_cprimme *c, int ldc, primme_context ctx);
int Num_gemv_magma_kprimme(const char *transa, PRIMME_INT m, int n, dummy_type_cprimme alpha,
      dummy_type_magma_kprimme *a, int lda, dummy_type_magma_kprimme *x, int incx, dummy_type_cprimme beta, dummy_type_magma_kprimme *y,
      int incy, primme_context ctx);
int Num_gemv_ddh_magma_kprimme(const char *transa, PRIMME_INT m, int n, dummy_type_cprimme alpha,
      dummy_type_magma_kprimme *a, int lda, dummy_type_magma_kprimme *x, int incx, dummy_type_cprimme beta, dummy_type_cprimme *y,
      int incy, primme_context ctx);
int Num_gemv_dhd_magma_kprimme(const char *transa, PRIMME_INT m, int n, dummy_type_cprimme alpha,
      dummy_type_magma_kprimme *a, int lda, dummy_type_cprimme *x, int incx, dummy_type_cprimme beta, dummy_type_magma_kprimme *y,
      int incy, primme_context ctx);
int Num_axpy_magma_kprimme(PRIMME_INT n, dummy_type_cprimme alpha, dummy_type_magma_kprimme *x, int incx,
   dummy_type_magma_kprimme *y, int incy, primme_context ctx);
dummy_type_cprimme Num_dot_magma_kprimme(PRIMME_INT n, dummy_type_magma_kprimme *x, int incx, dummy_type_magma_kprimme *y, int incy,
      primme_context ctx);
int Num_scal_magma_kprimme(PRIMME_INT n, dummy_type_cprimme alpha, dummy_type_magma_kprimme *x, int incx,
      primme_context ctx);
int Num_larnv_magma_kprimme(int idist, PRIMME_INT *iseed, PRIMME_INT length,
      dummy_type_magma_kprimme *x, primme_context ctx);
int Num_copy_matrix_magma_kprimme(dummy_type_magma_kprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, dummy_type_magma_kprimme *y, PRIMME_INT ldy,
      primme_context ctx);
int Num_zero_matrix_magma_kprimme(dummy_type_magma_kprimme *x, PRIMME_INT m, PRIMME_INT n,
      PRIMME_INT ldx, primme_context ctx);
int Num_trsm_hd_magma_kprimme(const char *side, const char *uplo, const char *transa,
      const char *diag, int m, int n, dummy_type_cprimme alpha, dummy_type_cprimme *a, int lda,
      dummy_type_magma_kprimme *b, int ldb, primme_context ctx);
#endif
